config/routes.rb
Rails.application.routes.draw do
  root 'dogs#index'

  get "icons/generate" => "icons#generate", format: :svg

  get "icontest" => "icons#test"

  resources :dogs do
    member do
      get 'badge' => 'dogs#badge', format: :svg
      get "generate" => "icons#generate", format: :svg
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
    @badgeURL = "#{request.base_url}/dogs/#{@dog.id}/badge.svg"
    @badgeURLGoodmeal = "https://oliviersandbox2.herokuapp.com/dogs/9/badge.svg"
  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_params)

    redirect_to dog_path(dog)
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])

    @dog.update(dog_params)

    redirect_to dog_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    redirect_to dogs_path
  end

  def badge
    @dog = Dog.find(params[:id])
    svg = '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="40" viewBox="0 0 400 40"><path fill="#303133" d="M11.547 40L0 20 11.547 0h360.467v40z"/>
    <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="77" y="27"> <%= @dog.name %></text>  
    <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="200" y="27"> <%= @dog.motto %></text>  
    
    <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="14" fill="#ECB613" x="32" y="18.77" text-anchor="middle" transform="translate(7 6)">5 kyu</text>
    </svg>'

    #{request.base_url}

    respond_to do |format|
      format.svg { render inline: svg}
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :motto)
  end

end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  def generate
    @dog = Dog.find(2)
    #svg = '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="40" viewBox="0 0 400 40"><path fill="#303133" d="M11.547 40L0 20 11.547 0h360.467v40z"/>
    #<text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="77" y="27"> <%= @dog.name %></text>  
    #<text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="200" y="27"> <%= @dog.motto %></text>  
    
    #<text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="14" fill="#ECB613" x="32" y="18.77" text-anchor="middle" transform="translate(7 6)">5 kyu</text>
    #</svg>'

    svg= '<svg width="270.933mm" height="30.1625mm"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  version="1.2" baseProfile="tiny">
    <desc>Created by EvoPdf</desc>
    <defs>
    </defs>
    <g fill="none" stroke="black" stroke-width="1" fill-rule="evenodd" stroke-linecap="square" stroke-linejoin="bevel" >
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    
    <g fill="#0000ff" fill-opacity="1" stroke="none" transform="matrix(1,0,0,1,0,0)"
    >
    <path vector-effect="none" fill-rule="evenodd" d="M8,8 L1016,8 L1016,106 L8,106 L8,8"/>
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(1,0,0,1,0,0)"
    >
    <text fill="#000000" fill-opacity="1" stroke="none" xml:space="preserve" x="8" y="37" font-family="Times New Roman" font-size="32" font-weight="700" font-style="normal" 
     >Coucou</text>
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(1,0,0,1,0,0)"
    >
    <text fill="#000000" fill-opacity="1" stroke="none" xml:space="preserve" x="8" y="81" font-family="Times New Roman" font-size="16" font-weight="400" font-style="normal" 
     ><%= @dog.motto %></text>
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="bevel" transform="matrix(1,0,0,1,0,0)"
    >
    <text fill="#000000" fill-opacity="1" stroke="none" xml:space="preserve" x="8" y="101" font-family="Times New Roman" font-size="16" font-weight="400" font-style="normal" 
     >Le restau &lt;%=@titre%&gt;</text>
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    
    <g fill="#000000" fill-opacity="1" stroke="#000000" stroke-opacity="1" stroke-width="1" stroke-linecap="square" stroke-linejoin="miter" stroke-miterlimit="2" transform="matrix(1,0,0,1,0,0)"
    >
    </g>
    </g>
    </svg>'
    

    respond_to do |format|
      format.svg { render inline: svg}
    end
  end

  def test
    @title = "Mon restau"
    @goodmeal = "Good Meal"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me in app/views/dogs/edit.html.erb</p>

app/views/dogs/index.html.erb
<div style="padding:30px;text-align:center">

<div style="display:inline-block">
<h1>Bienvenue sur Sandbox: l'app de test d'Olivier !!!</h1>
</div>

<ul>
  <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog_path(dog)  %></li>
  <% end %>
</ul>

<div><a href="https://oliviersandbox2.herokuapp.com/dogs/9/badge.svg"><img src="https://oliviersandbox2.herokuapp.com/dogs/9/badge.svg" alt="Badge from sandbox heroku"></a></div>

</div>

app/views/dogs/new.html.erb
<h1>Dogs#new</h1>
<p>Find me in app/views/dogs/new.html.erb</p>

app/views/dogs/show.html.erb
<h1>Dogs#show</h1>
<ul>
  <li><%= @dog.name %></li>
  <li><%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <li><%= link_to 'Badge', badge_dog_path(@dog) %></li>
  <li><%=@badgeURL%></li>
  <a href="<%=@badgeURL%>"> <img src="<%=@badgeURL%>" alt="Test de badge"></a>
</ul>

<% 
=begin %> 
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="40" viewBox="0 0 400 40"><path fill="#303133" d="M11.547 40L0 20 11.547 0h360.467v40z"/>
  <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="77" y="27"> <%= @dog.name %></text>  
  <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="20" fill="#E8E8E8" x="200" y="27"> <%= @dog.motto %></text>  
  
  <text font-family="Lato, HelveticaNeue, Helvetica Neue, Helvetica, Arial, sans-serif" font-size="14" fill="#ECB613" x="32" y="18.77" text-anchor="middle" transform="translate(7 6)">5 kyu</text>
  </svg>

<% 
=end %>

app/views/icons/test.html.erb
<div class="badge macaron">
  <div class="gm-logo">
    <img src="https://www.goodmeal.fr/assets/logo_new_blanc-5bda4380c201a0f8b742d7e7372ab220a222919fb5630e96e97a352c29563f87.png" alt="">
  </div>
  <h1>Coucou</h1>
  <span> <%=@goodmeal%> </span>
  <div>Le restau <%=@titre%> </div>
</div>
<%= image_tag ('icon-152x152.png') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SandboxRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>